"""Atlas — the mechanical maintainer of a Sector's map and invariants.

The Sector workflow stores all orienting state as YAML front-matter on the
cards — one card per branch/workstream. This script is the only thing that
turns that state into derived artifacts, so the derived artifacts can never
drift from their sources (Rebuild Plan §Phase 2; ported from the original
research repo's tools/atlas.py, resolved through sector_adapter so both the
research `notes/` layout and the programming `.sector/` layout work):

```text
<card>.md front-matter
        |
        +--> build : regenerate ATLAS.md            (the map; never hand-edited)
        +--> check : validate invariants             (exit 1 on violations)
        +--> gist  : print a branch's context gist   (--copy -> clipboard)
```

`check` is the piece that keeps the workflow honest: it catches half-stamped
supersession chains, dead context references, and stale cards left behind by
off-path sessions — run it at session open, fix what it flags, then start.

Usage (from the host repo root; --repo defaults to the current directory):
    python tools/sector/atlas.py check [--repo PATH] [--config PATH]
    python tools/sector/atlas.py build
    python tools/sector/atlas.py gist <branch> [--copy]
"""

import subprocess
import sys
from pathlib import Path

STARMAP_DIR = Path(__file__).resolve().parent
sys.path.insert(0, str(STARMAP_DIR))
import sector_adapter

ATLAS_HEADER = """# ATLAS — the Sector map

GENERATED by `atlas.py build` — never hand-edit this file.
Entry points: the cards listed below; context packs in the configured
context dir; workflow docs: tools/sector/docs/.
"""

# Card statuses, in the order the map displays them.
STATUS_ORDER = ["active", "forming", "dormant", "merged", "closed", "reference"]

# There is NO one-head-per-kind constraint: a branch runs any number of
# active plans/reports in parallel; chain integrity is fully carried by the
# bidirectional supersession stamps (a doc is "head" simply because nothing
# superseded it).


def card_name_of(meta: dict, folder: str) -> str:
    """The card's own idea of its name — `branch:` (research vocabulary) or
    `workstream:` (programming vocabulary); both are legal, folder as fallback."""
    return meta.get("branch") or meta.get("workstream") or folder


def load_cards(adapter):
    """Scan all branches -> (cards, uncarded_dirs, errors).

    cards: list of dicts {dir, path, meta, body}. Dirs without a card are the
    Archive tier — reported, never a violation. A dir with MULTIPLE candidate
    cards is an error (the one-card invariant).
    """
    cards, uncarded, errors = [], [], []
    for d in adapter.branch_dirs():
        found = adapter.find_card(d)
        if found is None:
            uncarded.append(d)
        elif isinstance(found, list):
            names = ", ".join(p.name for p in found)
            errors.append(f"{d.name}: multiple cards ({names}) — must be exactly one")
        else:
            meta, body = adapter.parse_front_matter(found)
            cards.append({"dir": d, "path": found, "meta": meta, "body": body})
    return cards, uncarded, errors


def extract_section(body: str, headings: list[str]):
    """Return the non-empty lines of the first `## <heading>` section that
    matches any of the given names (research cards say "Results", programming
    cards say "Working Claims" — the gist accepts either)."""
    wanted = {h.lower() for h in headings}
    lines, keep = [], False
    for line in body.splitlines():
        if line.startswith("## "):
            keep = line[3:].strip().lower() in wanted
            continue
        if keep and line.strip():
            lines.append(line.rstrip())
    return lines


def resolve_context_entry(adapter, entry: str) -> Path | None:
    """Resolve one `required_context` entry to the file that must exist.

    Both naming schemes are accepted, whichever the host's cards use:

    ```text
    "workflow:orchestrator"  (pack:variant)  -> <context>/workflow/orchestrator.md
    "env.testing"    (programming)  -> <context>/env/testing.md
    "env"            (bare pack)    -> <context>/env/INDEX.md, else <context>/env.md
    ```
    """
    entry = str(entry)
    for sep in (":", "."):
        if sep in entry:
            pack, _, variant = entry.partition(sep)
            return adapter.context_root / pack / f"{variant}.md"
    index = adapter.context_root / entry / "INDEX.md"
    if index.exists():
        return index
    return adapter.context_root / f"{entry}.md"


def declared_proofs(adapter, target: Path) -> list | None:
    """The proof list one live doc declares, read exactly where the starmap reads it.

    `check` and `server.py` must agree about this, or the map grows satellites
    the validator calls violations (plan step 2 item 7):

    ```text
    reviews/x.md   -> its own look_at, else the legacy proof_of_work
    reviews/x.html -> the stub reviews/x.md next to it (a page carries no
                      front-matter of its own)
    anything else  -> None, meaning the doc makes no checkable claim
    ```
    args: adapter, target (the live doc)
    returns: list of declared entries, or None when nothing is declared
    """
    if target.suffix.lower() in (".html", ".htm"):
        target = target.with_suffix(".md")
    if target.suffix != ".md" or not target.exists():
        return None
    meta = adapter.parse_front_matter(target)[0]
    declared = meta.get("look_at") or meta.get("proof_of_work")
    return None if declared is None else [str(x) for x in declared]


def declares(declared: list, entry: str) -> bool:
    """Whether a card-nested artifact is covered by the doc's own proof list,
    named directly or through a declared folder such as `artifacts/ui_reference/`.
    args: declared (the doc's list), entry (the card-nested path)
    returns: bool
    """
    return any(entry == d or (d.endswith("/") and entry.startswith(d)) for d in declared)


def build(adapter):
    """Regenerate ATLAS.md from card front-matter. Deterministic — merge
    conflicts are resolved by rerunning, never by hand."""
    cards, uncarded, errors = load_cards(adapter)
    out = [ATLAS_HEADER]
    by_status = {s: [] for s in STATUS_ORDER}
    for c in cards:
        by_status.setdefault(c["meta"].get("status", "unknown"), []).append(c)
    for status in list(STATUS_ORDER) + [s for s in by_status if s not in STATUS_ORDER]:
        group = by_status.get(status, [])
        if not group:
            continue
        out.append(f"\n## {status.capitalize()}\n")
        for c in sorted(group, key=lambda c: str(c["meta"].get("updated", "")), reverse=True):
            m = c["meta"]
            rel = c["path"].relative_to(adapter.repo).as_posix()
            waiting = len(m.get("check-me") or [])
            out.append(
                f"- **{c['dir'].name}**: {m.get('title', '(no title)')} "
                f"(updated {m.get('updated', '?')}, check-me {waiting}) -> `{rel}`"
            )
    if uncarded:
        out.append("\n## Archive (no card yet — adopt-on-touch)\n")
        for d in uncarded:
            out.append(f"- {d.name}")
    adapter.atlas_path.parent.mkdir(parents=True, exist_ok=True)
    adapter.atlas_path.write_text("\n".join(out) + "\n", encoding="utf-8")
    print(f"{adapter.atlas_path.name}: {len(cards)} cards, {len(uncarded)} archive dirs")
    for e in errors:
        print(f"ERROR: {e}")
    return 1 if errors else 0


def check(adapter):
    """Validate the Sector invariants. Prints violations; exit code 1 if any.

    Checks: card fields + name==folder; one card per branch; live_docs and
    required_context targets exist; supersession stamps are bidirectional —
    all enforced only among docs that HAVE front-matter (legacy files are
    invisible). Any number of head docs per kind is legal.
    """
    cards, _uncarded, violations = load_cards(adapter)

    for c in cards:
        m, d = c["meta"], c["dir"]
        where = c["path"].relative_to(adapter.repo).as_posix()
        for f in ("title", "status", "updated"):
            if not m.get(f):
                violations.append(f"{where}: missing front-matter field '{f}'")
        if not (m.get("branch") or m.get("workstream")):
            violations.append(f"{where}: missing front-matter field 'branch'/'workstream'")
        name = card_name_of(m, d.name)
        if name != d.name:
            violations.append(f"{where}: card name '{name}' != folder '{d.name}'")
        # SHIP_TODOS T13 (4): every live doc and every artifact nested under a
        # report must exist, and a nested artifact must be one the report's
        # own `look_at` list names (the card cannot promise a proof the report
        # does not show).
        for doc, arts in adapter.live_doc_entries(m):
            target = d / doc if (d / doc).exists() else adapter.repo / doc
            if not target.exists():
                violations.append(f"{where}: live_docs target missing: {doc}")
                continue
            look_at = declared_proofs(adapter, target)
            for a in arts:
                if not (d / a).exists() and not (adapter.repo / a).exists():
                    violations.append(f"{where}: live_docs artifact missing: {a} (under {doc})")
                elif look_at is not None and not declares(look_at, a):
                    violations.append(f"{where}: {a} nested under {doc} but absent from its look_at list")
        for item in m.get("check-me") or []:
            if not (d / str(item)).exists() and not (adapter.repo / str(item)).exists():
                violations.append(f"{where}: check-me target missing: {item}")
        for entry in m.get("required_context") or []:
            target = resolve_context_entry(adapter, entry)
            if target is not None and not target.exists():
                violations.append(f"{where}: required_context target missing: {entry}")

        # Supersession stamps, among stamped docs only.
        for sub in (adapter.plans_dir, adapter.reports_dir):
            for doc in sorted((d / sub).glob("*.md")) if (d / sub).is_dir() else []:
                meta, _ = adapter.parse_front_matter(doc)
                if not meta:
                    continue
                rel = doc.relative_to(d).as_posix()
                for field in ("supersedes", "superseded_by"):
                    target = meta.get(field)
                    if not target:
                        continue
                    # Stamps may be doc-relative ("handover_v1.md") or
                    # branch-relative ("reports/handover_v1.md") — accept both.
                    tpath = doc.parent / target
                    if not tpath.exists():
                        tpath = d / target
                    if not tpath.exists():
                        violations.append(f"{d.name}/{rel}: {field} target missing: {target}")
                        continue
                    tmeta, _ = adapter.parse_front_matter(tpath)
                    if field == "supersedes" and tmeta and tmeta.get("superseded_by") is None:
                        violations.append(
                            f"{d.name}/{target}: superseded by {rel} but carries no "
                            f"superseded_by back-stamp"
                        )
    for v in violations:
        print(f"VIOLATION: {v}")
    print(f"check: {len(cards)} cards, {len(violations)} violations")
    return 1 if violations else 0


def gist(adapter, branch: str, copy: bool = False):
    """Assemble the context gist for one branch and print it.

    Every line maps to a card field — the gist can never claim something the
    card doesn't: header <- name/status/updated; read list <- card + live_docs
    + resolved required_context; claims/landmines/graveyard <- the card's
    sections, verbatim; check-me <- front-matter. (The starmap composer is this
    same assembly as a GUI.)
    """
    d = adapter.branch_dir(branch)
    card = adapter.find_card(d) if d.is_dir() else None
    if card is None or isinstance(card, list):
        print(f"ERROR: no unique card for branch '{branch}'")
        return 1
    m, body = adapter.parse_front_matter(card)

    lines = [
        f"=== CONTEXT GIST: {branch} \"{m.get('title', '')}\" — "
        f"{m.get('status', '?')}, updated {m.get('updated', '?')} ===",
        "READ IN FULL, IN ORDER:",
        f"  1. {card.relative_to(adapter.repo).as_posix()}",
    ]
    n = 2
    for doc, arts in adapter.live_doc_entries(m):
        # Same resolution as check()/the server: branch-relative first, then
        # repo-relative, so cards may point at shared files outside the branch.
        target = d / doc
        if not target.exists() and (adapter.repo / doc).exists():
            target = adapter.repo / doc
        lines.append(f"  {n}. {target.relative_to(adapter.repo).as_posix()}")
        lines.extend(f"       proof: {a}" for a in arts)
        n += 1
    for entry in m.get("required_context") or []:
        target = resolve_context_entry(adapter, entry)
        lines.append(f"  {n}. {target.relative_to(adapter.repo).as_posix()}"
                     "        REQUIRED context")
        n += 1

    for label, headings in [("LIVE CLAIMS", ["Results", "Working Claims"]),
                            ("LANDMINES", ["Landmines"]),
                            ("RETIRED — DO NOT RE-DERIVE", ["Graveyard"])]:
        section = extract_section(body, headings)
        if section:
            lines.append(f"{label}:")
            lines.extend(f"  {s}" for s in section)
    waiting = m.get("check-me") or []
    if waiting:
        lines.append("CHECK ME (waiting for the owner's eyes): " + " | ".join(map(str, waiting)))
    lines.append("CONFIRM by restating: branch name, head doc filename+date, "
                 "every REQUIRED file.")

    text = "\n".join(lines)
    print(text)
    if copy:
        if sys.platform == "win32":
            subprocess.run("clip", input=text.encode("utf-16-le"), check=True)
        elif sys.platform == "darwin":
            subprocess.run("pbcopy", input=text.encode(), check=True)
        else:
            subprocess.run(["xclip", "-selection", "clipboard"], input=text.encode(), check=True)
    return 0


def main(argv):
    repo = Path.cwd()
    config_path = None
    if "--repo" in argv:
        repo = Path(argv[argv.index("--repo") + 1])
    if "--config" in argv:
        config_path = Path(argv[argv.index("--config") + 1])
    adapter = sector_adapter.load_adapter(
        repo=repo, starmap_dir=STARMAP_DIR, config_path=config_path)
    if len(argv) >= 1 and argv[0] == "build":
        return build(adapter)
    if len(argv) >= 1 and argv[0] == "check":
        return check(adapter)
    if len(argv) >= 2 and argv[0] == "gist":
        return gist(adapter, argv[1], copy="--copy" in argv)
    print(__doc__)
    return 2


if __name__ == "__main__":
    # Cards and gists carry arrows and em-dashes; a Windows console defaults to
    # cp1252 and would crash on the first one.
    for stream in (sys.stdout, sys.stderr):
        if hasattr(stream, "reconfigure"):
            stream.reconfigure(encoding="utf-8", errors="replace")
    sys.exit(main(sys.argv[1:]))
